/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registry.ui;

import java.awt.Component;
import java.awt.Dialog.ModalityType;
import java.awt.GridLayout;
import java.awt.Window;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;
import registry.RegValue.RegValueType;

/**
 *
 * @author henry.wang.1
 */
public class RegStringEditor extends JPanel implements RegValueEditor
{
	
	private static Window getWindow(Component c)
	{
		Component test = c;
		while (test != null)
		{
			if (test instanceof Window)
				return (Window) test;
			test = test.getParent();
		}
		return null;
	}
	
	private boolean canceled = false;
	private RegValueType type;
	
	
	public RegStringEditor()
	{
		initComponents();
	}
	
	@Override
	public Object showEditor(Window owner, String name, RegValueType type, Object val) {
		this.type = type;
		if (name.isEmpty())
			txtValueName.setText("(Default)");
		else
			txtValueName.setText(name);
		txtValueData.setText((String)val);
		
		canceled = true;
		JDialog dlg = new JDialog(owner, "Edit " + type.getShortName(), 
				ModalityType.APPLICATION_MODAL);
		dlg.getContentPane().setLayout(new GridLayout(1, 1));
		dlg.add(this);
		dlg.setResizable(false);
		dlg.pack();
		dlg.setLocationRelativeTo(owner);
		dlg.setVisible(true);
		
		System.out.println(canceled);
		if (canceled)
			return null;
		else
			return txtValueData.getText();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btngpBase = new javax.swing.ButtonGroup();
        lblValueName = new javax.swing.JLabel();
        txtValueName = new javax.swing.JTextField();
        lblValueData = new javax.swing.JLabel();
        txtValueData = new javax.swing.JTextField();
        pnlButtons = new javax.swing.JPanel();
        btnOkay = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        lblValueName.setText("Value Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        add(lblValueName, gridBagConstraints);

        txtValueName.setEditable(false);
        txtValueName.setText("<NAME>");
        txtValueName.setMinimumSize(new java.awt.Dimension(300, 20));
        txtValueName.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 0, 10);
        add(txtValueName, gridBagConstraints);

        lblValueData.setText("Value Data:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        add(lblValueData, gridBagConstraints);

        txtValueData.setMinimumSize(new java.awt.Dimension(100, 20));
        txtValueData.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 0, 10);
        add(txtValueData, gridBagConstraints);

        pnlButtons.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnOkay.setText("Okay");
        btnOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkayActionPerformed(evt);
            }
        });
        pnlButtons.add(btnOkay);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        add(pnlButtons, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        canceled = true;
		getWindow(this).setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkayActionPerformed
        canceled = false;
		getWindow(this).setVisible(false);
    }//GEN-LAST:event_btnOkayActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOkay;
    private javax.swing.ButtonGroup btngpBase;
    private javax.swing.JLabel lblValueData;
    private javax.swing.JLabel lblValueName;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JTextField txtValueData;
    private javax.swing.JTextField txtValueName;
    // End of variables declaration//GEN-END:variables

}
